---
roq:

  systemd:
    user: ubuntu
    group: ubuntu
    start: '*-*-* 00:01:00'
    stop: '*-*-* 23:59:00'
    restart: 'no'

  common:

    auth_keys:
       public_key: MKthNtwskvDD25RqppN2DEb9DzqoqtOupWVp_IdJoGc=
       secret_key: dbRsI7hF2SaoYqsfIPJMyYegcnbVmEoZ7yhoL6HzYHI=

    flags:  # note! gateways
      secrets_file: "/home/ubuntu/.secret/roq.toml"
      loop_sleep: 500ns
      loop_timer_freq: 2500ns
      event_log_iso_week: false
      event_log_symlink: true
      cache_mbp_checksum: false
      cache_all_reference_data: true
      cache_database_uri: "http://localhost:8123"
      cache_database_name: "roq_cache"
      oms_cache: true
      enable_risk: true

  services:

    binance:
      package: roq-binance
      logging:
        verbosity: 0
      environment: prod
      flags:
        download_trades_lookback: 24h
        rest_cancel_on_disconnect: false
      config:
        symbols:
          - "^BTCUSD[A-Z]?$"
          - "^ETHUSD[A-Z]?$"
        accounts:
          A1:
            login: "DIyBxTrPYW9KOxMBvOowUfmC6Kbv4DUgyBw3K5su2E2D3VuNSziUHn3yyFjEehd9"
            symbols: .*
            master: true
        users:
          trader:
            password: secret
            accounts: A1
            symbols: ".*"
          sbe-publisher:
            password: secret
          fix-bridge:
            password: secret
            accounts: A1
            symbols:
              - "^BTCUSD[A-Z]?$"

    bybit:
      package: roq-bybit
      logging:
        verbosity: 0
      environment: prod
      flags:
        download_trades_lookback: 24h
      config:
        symbols:
          - "^BTCUSD$"
          - "^BTCUSDT$"
          - "^BTC-.*-[PC]$"
        accounts:
          A1:
            login: "BBFAYIXRZYKVZBFJDQ"
            symbols: .*
            master: true
        users:
          trader:
            password: secret
            accounts: A1
            symbols: ".*"
          sbe-publisher:
            password: secret
          fix-bridge:
            password: secret
            accounts: A1
            symbols:
              - "^BTCUSDT$"
              - "^BTC-.*-[PC]$"

    deribit:
      package: roq-deribit
      logging:
        verbosity: 0
      environment: prod
      flags:
        download_trades_lookback: 24h
        fix_cancel_on_disconnect: false
      config:
        symbols:
          - "^BTC-[0-9]{1,2}[A-Z]{3}[0-9]{2}$"  # futures
          - "^ETH-[0-9]{1,2}[A-Z]{3}[0-9]{2}$"  # futures
          - "^BTC(_USD[A-Z]?)?-PERPETUAL$"  # swaps
          - "^ETH(_USD[A-Z]?)?-PERPETUAL$"  # swaps
          - "^BTC(-USD[A-Z]?)?-DERIBIT-INDEX$"  # index
          - "^ETH(-USD[A-Z]?)?-DERIBIT-INDEX$"  # index
        accounts:
          A1:
            login: "UkwIGQ7P"
            symbols: .*
            master: true
        users:
          trader:
            password: secret
            accounts: A1
            symbols: "BTC-PERPETUAL"
          sbe-publisher:
            password: secret
          fix-bridge:
            password: secret
            accounts: A1
            symbols:
              - "^BTC-[0-9]{1,2}[A-Z]{3}[0-9]{2}$"  # futures
              - "^BTC(_USD[A-Z]?)?-PERPETUAL$"  # swaps

    okx:
      package: roq-okx
      logging:
        verbosity: 0
      environment: prod
      flags:
        download_trades_lookback: 24h
      config:
        symbols:
          - "^BTC-USD[A-Z]$"  # spot
          - "^ETH-USD[A-Z]$"  # spot
          - "^PERP-USD[A-Z](-SWAP)?$"  # swaps
        accounts:
          A1:
            login: "9e7751fa-ad03-4296-a8eb-4ff64aca7214"
            password: "B#gck5RS6^S2iHpk"
            symbols: .*
            master: true
        users:
          trader:
            password: secret
            accounts: A1
            symbols: "PERP-USDT"
          sbe-publisher:
            password: secret
          fix-bridge:
            password: secret
            accounts: A1
            symbols:
              - "^BTC-USD[A-Z]$"  # spot
              - "^PERP-USD[A-Z](-SWAP)?$"  # swaps

    sbe-publisher:
      package: roq-sbe-publisher
      logging:
        verbosity: 0
      environment: prod
      dependencies:
        - deribit
      flags:
        local_interface: 172.31.45.190  # note! ip route get 8.8.8.8
        multicast_address_snapshot: 224.1.1.1
        multicast_port_snapshot: 5678
        multicast_address_incremental: 224.1.1.2
        multicast_port_incremental: 6789
        multicast_ttl: 4
        multicast_loop: true
        max_depth: 5
      config:
        symbols:
          - ["USD.*", "BTC.*"]
          - deribit:
              - "BTC-PERPETUAL"
              - "ETH-PERPETUAL"

    drop-copy:
      package: roq-drop-copy
      logging:
        verbosity: 0
      environment: prod
      dependencies:
        - deribit
      flags:
        database_uri: "http://localhost:8123"
        database_name: "roq_drop_copy"
      config:
        symbols: ".*"

    fix-bridge:
      package: roq-fix-bridge
      logging:
        verbosity: 0
      environment: prod
      dependencies:
        - deribit
      flags:
        fix_comp_id: "fix-bridge"
        init_missing_md_entry_type_to_zero: true
        oms_route_by_strategy: true
      config:
        symbols:
          - ["USD.*", "BTC.*"]
          - deribit:
              - "BTC-PERPETUAL"
              - "ETH-PERPETUAL"
        users:
          md1:
            component: "md1"
            username: "md1"
          fix-proxy:
            component: "fix-proxy"
            username: "oe1"
            password: "secret"
        statistics: {}

    fix-proxy:
      package: roq-fix-proxy
      logging:
        verbosity: 0
      environment: prod
      dependencies:
        - fix-bridge
      flags:
        auth_uri: "ws://localhost:1234"
        client_listen_address: "tcp://localhost:3333"
        server_target_comp_id: "fix-bridge"
        server_sender_comp_id: "fix-proxy"
        server_username: "oe1"
        server_password: "secret"
        client_comp_id: "mp-fix-proxy"
      config:
        symbols: ["USD.*", "BTC.*"]
        users:
          c1:
            component: "test"
            username: "c1"
            password: "p1"
            accounts: "A1"
            strategy_id: 1

    fix-config:
      package: roq-fix-config
      logging:
        verbosity: 0
      environment: prod
      dependencies: {}
      flags:
        client_listen_address: 1234
      config:
        users:
          c1:
            component: "test"
            username: "c1"
            password: "p1"
            accounts: "A1"
            strategy_id: 1
          c2:
            component: "test"
            username: "c2"
            password: "p2"
            accounts: "A2"
            strategy_id: 2
          c3:
            component: "test"
            username: "c3"
            password: "p3"
            accounts: ["A1", "A2"]
            strategy_id: 3

    cache-proxy-1:
      package: roq-cache-proxy
      logging:
        verbosity: 0
      environment: prod
      dependencies: {}
      flags:
        multicast_port: 4567
        multicast_address: 224.1.1.3
        local_interface: 172.31.45.190  # note! ip route get 8.8.8.8
        database_uri: "http://localhost:8123"
        database_name: "roq_cache"
        cache_dir: "/var/lib/roq/cache-proxy-1"
        cache_datasync: true
        cache_datasync_before_respond: false

container:
  solution: docker

prometheus:
  scrape_configs:
    - binance
    - bybit
    - deribit
    - okx

nginx:
  port: 2023
