---
roq:

  systemd:
    user: ansible
    group: ansible
    start: '*-*-* 00:01:00'
    stop: '*-*-* 23:59:00'
    restart: 'no'

  common:

    auth_keys:
       public_key: YOUR_ROQ_PUBLIC_KEY
       secret_key: YOUR_ROQ_PRIVATE_KEY

    flags:
      loop_sleep: 500ns
      loop_timer_freq: 2500ns
      event_log_iso_week: false
      event_log_symlink: true
      cache_mbp_checksum: false
      cache_all_reference_data: true

  services:

    deribit:
      package: roq-deribit
      logging:
        verbosity: 0
      environment: test
      flags: {}
      config:
        symbols:
          - ^BTC-[0-9]{1,2}[A-Z]{3}[0-9]{2}$  # futures
          - ^ETH-[0-9]{1,2}[A-Z]{3}[0-9]{2}$  # futures
          - ^BTC(_USD[A-Z]?)?-PERPETUAL$  # swaps
          - ^ETH(_USD[A-Z]?)?-PERPETUAL$  # swaps
          - ^BTC(-USD[A-Z]?)?-DERIBIT-INDEX$  # index
          - ^ETH(-USD[A-Z]?)?-DERIBIT-INDEX$  # index
        accounts:
          A1:
            login: YOUR_DERIBIT_PUBLIC_KEY
            secret: YOUR_DERIBIT_PRIVATE_KEY
            symbols: .*
            master: true
        users:
          trader:
            password: secret
            accounts: A1
            symbols: BTC-\\d{2}\\D{3}\\d{2}
          fix-bridge:
            password: secret
            accounts: A1
            symbols:
              - ^BTC-[0-9]{1,2}[A-Z]{3}[0-9]{2}$  # futures
              - ^BTC(_USD[A-Z]?)?-PERPETUAL$  # swaps

container:
  solution: docker

prometheus:
  scrape_configs:
    - deribit

nginx:
  port: 1234
